Document: pixel-wallpaper
Title: Debian pixel-wallpaper Manual
Author: <insert document author here>
Abstract: This manual describes what pixel-wallpaper is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pixel-wallpaper/pixel-wallpaper.sgml.gz

Format: postscript
Files: /usr/share/doc/pixel-wallpaper/pixel-wallpaper.ps.gz

Format: text
Files: /usr/share/doc/pixel-wallpaper/pixel-wallpaper.text.gz

Format: HTML
Index: /usr/share/doc/pixel-wallpaper/html/index.html
Files: /usr/share/doc/pixel-wallpaper/html/*.html
